name                "apache"
maintainer          "Julien Guittard"
maintainer_email    "julien.guittard@me.com"
license             "All Rights Reserved"
description         "Configure Apache Virtual Hosts"
version             "0.1.0"
